name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push Docker image for Frontend
      run: |
        docker build --push --build-arg NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }} -t ${{ secrets.ACR_LOGIN_SERVER }}/pact-frontend:latest .

    - name: Deploy frontend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_SERVICE_FRONTEND }} 
        images: |
          ${{ secrets.ACR_LOGIN_SERVER }}/pact-frontend:latest
